const studioMessages: Record<string, string> = {
  'nav.studio': 'Studio',
  'nav.studio.text': 'Text Generation',
  'nav.studio.image': 'Image Generation',
  'nav.studio.video': 'Video Generation',
  'header.signIn': 'Sign In',
  'header.signOut': 'Sign out',
  'header.account': 'Account',
  'header.loggedIn': 'Signed in',
  'header.getStartedFree': 'Get Started Free',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.clear': 'Clear',
  'common.processing': 'Processing…',
  'common.upload': 'Upload',
  'common.failed': 'Failed',
  'imageGen.promptPlaceholder':
    'Describe the image you want, e.g. a cute orange cat on a grey sofa.',
  'imageGen.uploadHint':
    'Click or drag images here (paste supported). Up to {count} reference images.',
  'imageGen.label.model': 'Model',
  'imageGen.modelLoading': 'Loading models…',
  'imageGen.modelEmpty': 'No image models available',
  'imageGen.label.aspect': 'Aspect ratio',
  'imageGen.label.quality': 'Quality',
  'imageGen.generate': 'Generate',
  'imageGen.generating': 'Generating…',
  'imageGen.error.noModel': 'Please select a model.',
  'imageGen.error.promptRequired': 'Please enter a prompt.',
  'imageGen.ws.error': 'WebSocket error. Please try again.',
  'imageGen.ws.emptyDataList': 'Generation failed: no images were returned.',
  'imageGen.ws.noResultUrl': 'Generation failed: could not get image URLs.',
  'imageGen.ws.server500': 'Generation failed: AI processing error.',
  'imageGen.ws.insufficientBalance': 'Insufficient balance. Please recharge.',
  'imageGen.ws.generateFailed': 'Generation failed.',
  'imageGen.upload.failed': 'Image upload failed. Please try again.',
  'imageGen.upload.inProgress': 'Please wait for images to finish uploading.',
  'imageGen.upload.maxReached': 'Maximum number of reference images reached.',
  'imageGen.upload.invalidType': 'Please choose an image file.',
  'imageGen.action.reEdit': 'Re-edit',
  'imageGen.action.regenerate': 'Generate again',
  'imageGen.action.more': 'More options',
  'imageGen.action.delete': 'Delete',
  'imageGen.action.download': 'Download',
  'imageGen.action.downloadSuccess': 'Download started.',
  'imageGen.action.downloadFailed': 'Failed to download.',
  'imageGen.action.deleteConfirm.title': 'Delete this image?',
  'imageGen.action.deleteConfirm.description':
    'This record will be removed from your list. This cannot be undone.',
  'imageGen.action.deleteSuccess': 'Deleted.',
  'imageGen.action.deleteFailed': 'Failed to delete.',
  'imageGen.history.loading': 'Loading history…',
  'imageGen.history.loadingMore': 'Loading earlier messages…',
  'imageGen.history.loadFailed': 'Failed to load history.',
  'videoGen.promptPlaceholder':
    'Describe the video you want, e.g. a cute orange cat jumping on a grey sofa.',
  'videoGen.uploadHint':
    'Click or drag images here (paste supported). Up to {count} reference images.',
  'videoGen.label.model': 'Model',
  'videoGen.modelLoading': 'Loading models…',
  'videoGen.modelEmpty': 'No video models available',
  'videoGen.label.frameMode': 'Frame mode',
  'videoGen.frameMode.firstFrame': 'First frame',
  'videoGen.frameMode.firstLastFrame': 'First & last frame',
  'videoGen.frameSlot.first': 'First Frame',
  'videoGen.frameSlot.last': 'Last Frame',
  'videoGen.uploadHintFirstFrame':
    'Click or drag an image here (paste supported) as the first frame.',
  'videoGen.uploadHintFirstLastFrame':
    'Click or drag images here (paste supported). Upload first and last frame (up to 2).',
  'videoGen.label.aspect': 'Aspect ratio',
  'videoGen.label.quality': 'Quality',
  'videoGen.label.duration': 'Duration',
  'videoGen.generate': 'Generate',
  'videoGen.generating': 'Generating…',
  'videoGen.error.noModel': 'Please select a model.',
  'videoGen.error.promptRequired': 'Please enter a prompt.',
  'videoGen.ws.error': 'WebSocket error. Please try again.',
  'videoGen.ws.emptyDataList': 'Generation failed: no videos were returned.',
  'videoGen.ws.noResultUrl': 'Generation failed: could not get video URLs.',
  'videoGen.ws.server500': 'Generation failed: AI processing error.',
  'videoGen.ws.insufficientBalance': 'Insufficient balance. Please recharge.',
  'videoGen.ws.generateFailed': 'Generation failed.',
  'videoGen.upload.failed': 'Image upload failed. Please try again.',
  'videoGen.upload.inProgress': 'Please wait for images to finish uploading.',
  'videoGen.upload.maxReached': 'Maximum number of reference images reached.',
  'videoGen.upload.invalidType': 'Please choose an image file.',
  'videoGen.action.reEdit': 'Re-edit',
  'videoGen.action.regenerate': 'Generate again',
  'videoGen.action.more': 'More options',
  'videoGen.action.delete': 'Delete',
  'videoGen.action.download': 'Download',
  'videoGen.action.downloadSuccess': 'Download started.',
  'videoGen.action.downloadFailed': 'Failed to download.',
  'videoGen.action.deleteConfirm.title': 'Delete this video?',
  'videoGen.action.deleteConfirm.description':
    'This record will be removed from your list. This cannot be undone.',
  'videoGen.action.deleteSuccess': 'Deleted.',
  'videoGen.action.deleteFailed': 'Failed to delete.',
  'videoGen.history.loading': 'Loading history…',
  'videoGen.history.loadingMore': 'Loading earlier messages…',
  'videoGen.history.loadFailed': 'Failed to load history.',
  'generator.message.thinkingTitle': 'Thinking Deeply',
  'generator.message.modelFallback': 'Model',
  'generator.textGenerator.newChatButton': 'New Chat',
  'generator.textGenerator.newChatTitle': 'New chat',
  'generator.textGenerator.noChatYet': 'No chat history yet',
  'generator.textGenerator.feature.deepThinking': 'Deep thinking',
  'generator.textGenerator.feature.webSearch': 'Web search',
  'generator.textGenerator.attachMenu.open': 'Attach',
  'generator.textGenerator.attachMenu.uploadFile': 'Upload file',
  'generator.textGenerator.attachMenu.uploadImage': 'Upload image',
  'generator.textGenerator.attach.uploading': 'Uploading...',
  'generator.textGenerator.attach.uploadFailed': 'Upload failed',
  'generator.textGenerator.attach.remove': 'Remove attachment',
  'generator.textGenerator.chatList.moreLabel': 'Conversation actions',
  'generator.textGenerator.chatList.rename': 'Rename',
  'generator.textGenerator.chatList.delete': 'Delete',
  'generator.textGenerator.chatList.renameDialogTitle': 'Rename conversation',
  'generator.textGenerator.chatList.renamePlaceholder': 'Conversation title',
  'generator.textGenerator.chatList.renameSave': 'Save',
  'generator.textGenerator.chatList.renameCancel': 'Cancel',
  'generator.textGenerator.chatList.renameEmpty': 'Title cannot be empty.',
  'generator.textGenerator.chatList.renameSuccess': 'Title updated.',
  'generator.textGenerator.chatList.renameError': 'Failed to rename.',
  'generator.textGenerator.chatList.deleteConfirmTitle': 'Delete conversation?',
  'generator.textGenerator.chatList.deleteConfirmBody':
    'This conversation will be removed from your list. This cannot be undone.',
  'generator.textGenerator.chatList.deleteConfirm': 'Delete',
  'generator.textGenerator.chatList.deleteCancel': 'Cancel',
  'generator.textGenerator.chatList.deleteSuccess': 'Conversation deleted.',
  'generator.textGenerator.chatList.deleteError': 'Failed to delete.',
  'generator.textGenerator.chatList.historyTitle': 'Conversation history',
  'generator.textGenerator.chatList.clearAll': 'Clear all',
  'generator.textGenerator.chatList.clearAllAria': 'Clear all conversations',
  'generator.textGenerator.chatList.clearAllConfirmTitle': 'Clear all conversations?',
  'generator.textGenerator.chatList.clearAllConfirmBody':
    'All conversations in the list will be removed. This cannot be undone.',
  'generator.textGenerator.chatList.clearAllConfirm': 'Clear all',
  'generator.textGenerator.chatList.clearAllCancel': 'Cancel',
  'generator.textGenerator.chatList.clearAllSuccess': 'All conversations cleared.',
  'generator.textGenerator.chatList.clearAllError': 'Failed to clear conversations.',
  'generator.textGenerator.modelConfig.openButton': 'Model settings',
  'generator.textGenerator.modelConfig.title': 'Model configuration',
  'generator.textGenerator.modelConfig.systemPrompt': 'System prompt',
  'generator.textGenerator.modelConfig.systemPromptPlaceholder': 'Enter system prompt…',
  'generator.textGenerator.modelConfig.maxMessageCount': 'Max message count',
  'generator.textGenerator.modelConfig.temperature': 'Temperature',
  'generator.textGenerator.modelConfig.topP': 'Top P',
  'generator.textGenerator.modelConfig.maxOutputTokens': 'Max output tokens',
  'generator.textGenerator.modelConfig.reset': 'Reset',
  'generator.textGenerator.modelConfig.save': 'Save',
  'generator.textGenerator.modelConfig.close': 'Close',
  'generator.textGenerator.modelConfig.hint.systemPrompt':
    'Prompts guide how the model behaves and responds—for example: “You are a professional programming assistant” or “Keep answers concise.”',
  'generator.textGenerator.modelConfig.hint.maxMessageCount':
    'Sets how many past messages are kept in the conversation history, which affects how well the model understands context.',
  'generator.textGenerator.modelConfig.hint.temperature':
    'Controls randomness: higher values are more varied and creative; lower values are more deterministic and conservative.',
  'generator.textGenerator.modelConfig.hint.topP':
    'Controls vocabulary diversity in nucleus sampling: higher values explore more words; lower values stay closer to the most likely tokens.',
  'generator.textGenerator.modelConfig.hint.maxOutputTokens':
    'Caps the maximum length of each reply; more tokens allow longer answers but consume more resources.',
  'models.card.inputLabel': 'Input',
  'models.card.outputLabel': 'Output',
  'tgPlayground.emptyHint': 'How can I help you today?',
  'modelDetail.back': 'Back',
  'modelDetail.loading': 'Loading…',
  'modelDetail.notFound': 'Model not found: {id}',
  'modelDetail.inputTokens': 'Input tokens',
  'modelDetail.outputTokens': 'Output tokens',
  'modelDetail.inputType': 'Input type',
  'modelDetail.outputType': 'Output type',
  'modelDetail.pricingDetails': 'Pricing details',
  'modelDetail.pricing.groupLabel': 'Group',
  'modelDetail.pricing.condition': 'When {criteria}',
  'modelDetail.pricing.perMInput': '/M input tokens',
  'modelDetail.pricing.perMOutput': '/M output tokens',
  'modelDetail.pricing.searchLabel': 'Web search',
  'modelDetail.pricing.imageLabel': 'Image',
  'modelDetail.pricing.secondLabel': 'Per second',
  'modelDetail.pricing.characterLabel': 'Per character',
  'modelDetail.tabs.playground': 'Playground',
  'modelDetail.tabs.api': 'API',
  'modelDetail.tabs.requests': 'Requests',
  'modelDetail.tabs.price': 'Pricing',
  'modelDetail.pricing.empty': 'No pricing information available.',
  'modelDetail.chat': 'Chat',
  'modelDetail.playground.input': 'Input',
  'modelDetail.playground.output': 'Output',
  'modelDetail.playground.promptPlaceholder': 'Enter a prompt…',
  'modelDetail.playground.promptDesc': 'A text description of the desired output',
  'modelDetail.playground.imageDesc': 'Upload a reference image',
  'modelDetail.playground.videoUploadDesc':
    'Upload reference image(s) for video generation (same /v1/predictions flow; use function: video for video output models).',
  'modelDetail.playground.audioDesc': 'Upload an audio file',
  'modelDetail.playground.fileDesc': 'Upload a file',
  'modelDetail.playground.maxChars': 'Max {n} characters',
  'modelDetail.playground.maxImages': 'Upload up to {n} images',
  'modelDetail.playground.maxAudios': 'Upload up to {n} audio files',
  'modelDetail.playground.reset': 'Reset',
  'modelDetail.playground.run': 'Run',
  'modelDetail.playground.signInToRun': 'Sign in to run',
  'modelDetail.playground.preview': 'Preview',
  'modelDetail.playground.json': 'JSON',
  'modelDetail.playground.imageJsonInvalid':
    'Fix JSON errors or switch to the Form tab before running.',
  'modelDetail.playground.imageUploadFailed': 'Image upload failed.',
  'modelDetail.playground.imageGenFailed': 'Image generation failed.',
  'modelDetail.playground.predictionNoOutput':
    'No image or video URL in the task result.',
  'modelDetail.playground.imagePolling': 'Processing… will check again in 10s.',
  'modelDetail.playground.generating': 'Submitting…',
  'modelDetail.playground.outputJsonPlaceholder':
    'After a successful run, the JSON from GET /v1/predictions/<task_id> will appear here.',
  'modelDetail.requests.signInHint': 'Sign in to load your request history.',
  'modelDetail.requests.signInCta': 'Sign in',
  'modelDetail.requests.noModelId':
    'Missing model ID from detail API; cannot load request log.',
  'apiSubmitPanel.tabs.form': 'Form',
  'apiSubmitPanel.tabs.json': 'JSON',
  'apiSubmitPanel.tabs.http': 'HTTP',
  'apiSubmitPanel.copy': 'Copy',
  'apiSubmitPanel.copied': 'Copied',
  'apiSubmitPanel.uploadImageFile': 'Upload image file',
  'apiSubmitPanel.uploadAudioFile': 'Upload audio file',
  'apiSubmitPanel.clickUploadImage': 'Click to upload image',
  'apiSubmitPanel.clickUploadAudio': 'Click to upload audio',
  'apiSubmitPanel.selectedCount': '({count} selected)',
  'apiSubmitPanel.imageFormats': 'Supports JPG, PNG, WebP, GIF, etc.',
  'apiSubmitPanel.audioFormats': 'Supports MP3, WAV, M4A, etc.',
  'apiSubmitPanel.removeFile': 'Remove file',
  'apiSubmitPanel.selectPlaceholder': 'Please select',
  'apiSubmitPanel.secretShow': 'Show',
  'apiSubmitPanel.secretHide': 'Hide',
  'apiSubmitPanel.jsonError': 'JSON error: {error}',
  'apiSubmitPanel.jsonSyncHint': 'Editing JSON will sync form values',
  'apiSubmitPanel.httpDocLoading': 'Loading HTTP documentation...',
  'apiSubmitPanel.httpDocLoadError': 'Failed to load markdown: {error}',
  'apiSubmitPanel.httpDocEmpty': 'No markdown content.',
  'apiSubmitPanel.booleanOn': 'On',
  'apiSubmitPanel.booleanOff': 'Off',
  'apiSubmitPanel.booleanSwitch': 'Toggle {label}',
  'account.logs.filter.time': 'Time',
  'account.logs.filter.timePlaceholder': 'Select date range',
};

export function t(key: string): string {
  return studioMessages[key] ?? key;
}

/** Drop-in replacement for the source project's useI18n hook (English only). */
export function useI18n() {
  return { t, locale: 'en' as const };
}
